# Generated by Django 4.2.11 on 2024-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_profile_course_title_profile_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
